apply plugin: 'com.android.library'

android {
    compileSdkVersion 33
    defaultConfig {
        targetSdkVersion 33
        minSdkVersion 26
//        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    namespace 'com.fde.dialogtiplib'
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
