apply plugin: 'com.android.application'
//apply plugin: 'com.tencent.matrix-plugin'

android {
    namespace 'com.fde.x11'
    compileSdkVersion 33
    defaultConfig {
        applicationId "com.fde.x11"
        minSdkVersion 26
        targetSdkVersion 33
        versionCode 149
        versionName "1.4.9"
        buildConfigField "String", "COMMIT", "\"" + ("git rev-parse HEAD\n".execute().getText().trim() ?: (System.getenv('CURRENT_COMMIT') ?: "NO_COMMIT")) + "\""
        manifestPlaceholders = [MainActivityMinHeight: "50dp",
                                MainActivityMinWidth: "50dp",
                                MainDialogMinHeight: "50dp",
                                MainDialogMinWidth: "50dp"]
        externalNativeBuild {
            cmake {
                arguments "-DAPP_LOG=1"
            }
        }
    }

    applicationVariants.all { variant ->
        variant.outputs.all { output ->
            def project = "fdex11"
            def separator = "-"
            def buildType = variant.buildType.name
            def version = variant.versionName
            def newApkName =
                    "${project}${separator}${buildType}${separator}${version}.apk"

            output.outputFileName = newApkName
        }
    }


    signingConfigs {
        debug {
            keyAlias 'androiddebugkey'
            keyPassword 'android'
            storeFile file('plugin.keystore')
            storePassword 'android'
        }

        release {
            keyAlias 'androiddebugkey'
            keyPassword 'android'
            storeFile file('plugin.keystore')
            storePassword 'android'
        }
    }


    splits.abi {
        enable true
        reset()

        include "arm64-v8a"
    }

    buildFeatures {
        viewBinding = true
    }

    lintOptions {
        disable "Instantiatable"
    }

    externalNativeBuild.cmake.path "src/main/cpp/CMakeLists.txt"
//    packagingOptions.jniLibs.useLegacyPackaging false
    buildFeatures.aidl true
    buildFeatures.buildConfig true
    buildTypes {
        release {
            signingConfig signingConfigs.release
            externalNativeBuild {
                cmake {
                    arguments "-DAPP_LOG=0" // Debug模式开启日志
                }
            }
        }
        debug {
            externalNativeBuild {
                cmake {
                    arguments "-DAPP_LOG=1" // Debug模式开启日志
                }
            }
        }
    }


    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    flavorDimensions "systemv"

    productFlavors {
        versionu {
            dimension "systemv"
            buildConfigField "String", "system_verstion", "\"versionu\""
        }

        versionr {
            dimension "systemv"
            buildConfigField "String", "system_verstion", "\"versionr\""
        }
    }

    sourceSets {
        versionu.java.srcDirs = ['src/versionu/java']
        versionr.java.srcDirs = ['src/versionr/java']
    }


}

android.applicationVariants.all { variant ->
    variant.javaCompileProvider.configure { javaCompile ->
        def flavorName = variant.flavorName
        def frameworkJar = file("libs/${flavorName}/framework.jar")

        // 更新 bootstrapClasspath
        def originalBootstrap = javaCompile.options.bootstrapClasspath?.files ?: [] as Set
        javaCompile.options.bootstrapClasspath = files(frameworkJar) + files(originalBootstrap)
    }
}

dependencies {
    compileOnly fileTree(include: ['*.jar'], dir: 'libs/compile')
    implementation fileTree(include: ['*.jar'], dir: 'libs/impl')
    versionuCompileOnly files('libs/versionu/framework.jar')
    versionrCompileOnly files('libs/versionr/framework.jar')
    compileOnly files('libs/openfde_sdk.jar')

//    compileOnly files('libs/framework.jar')
    //noinspection DifferentStdlibGradleVersion
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.0'
    implementation 'androidx.preference:preference:1.2.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'com.google.android.material:material:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.3'
    implementation 'com.xwdz:okHttpUtils:1.3.0'
    implementation 'com.squareup.okhttp3:okhttp:3.5.0'
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
    implementation 'com.caverock:androidsvg:1.4'
    implementation 'io.github.razerdp:BasePopup:3.2.1'
    implementation 'org.greenrobot:eventbus:3.2.0'
    implementation 'com.github.ChickenHook:RestrictionBypass:2.2'

    implementation project(':x_recyclerview')
    implementation project(':fusionwindowmanager')
    implementation project(':dialogtiplib')
    implementation project(':easy')

//    debugImplementation ("com.squareup.leakcanary:leakcanary-android:2.5")
}
