apply plugin: 'com.android.library'

android {
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 33
        consumerProguardFiles 'proguard-rules.txt'
    }

    resourcePrefix 'x_recycler'
    namespace 'com.fde.recyclerview'
}

dependencies {
    implementation 'androidx.recyclerview:recyclerview:1.0.0'
}
